import type { ArchiveItem } from './db.ts';
import type { StationData } from '../src/types/polaris.ts';

// Generated downloads. The archive holds metadata only (no multi-GB payloads),
// so dataset downloads are small, clearly labelled sample extracts built from
// the record's metadata with a deterministic generator.

function rng(seedText: string) {
  let h = 2166136261;
  for (const c of seedText) h = Math.imul(h ^ c.charCodeAt(0), 16777619);
  return () => {
    h = Math.imul(h ^ (h >>> 15), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    return ((h ^= h >>> 16) >>> 0) / 4294967296;
  };
}

function num(text: string, fallback = 0): number {
  const m = String(text).replace(/,/g, '').match(/[-+]?\d+(\.\d+)?/);
  return m ? parseFloat(m[0]) : fallback;
}

const round = (v: number, d = 2) => Math.round(v * 10 ** d) / 10 ** d;

interface Variable {
  name: string;
  units: string;
  longName: string;
  base: number;
  amp: number;
  noise: number;
}

function variablesFor(item: ArchiveItem): Variable[] {
  const text = `${item.title} ${item.summary} ${item.domain} ${item.tags.join(' ')}`.toLowerCase();
  if (/lidar|aerosol|aod|radiometr/.test(text))
    return [
      { name: 'aerosol_optical_depth', units: '1', longName: 'Aerosol Optical Depth at 500 nm', base: 0.042, amp: 0.012, noise: 0.004 },
      { name: 'cloud_base_height', units: 'm', longName: 'Cloud base height above ground', base: 1420, amp: 380, noise: 120 },
    ];
  if (/met|synop|wind|ozone/.test(text))
    return [
      { name: 'air_temperature', units: 'degC', longName: 'Air temperature at 2 m', base: -14, amp: 4, noise: 0.8 },
      { name: 'wind_speed', units: 'kt', longName: 'Wind speed at 10 m', base: 18, amp: 6, noise: 2 },
      { name: 'total_ozone_column', units: 'DU', longName: 'Total ozone column', base: 284, amp: 20, noise: 4 },
    ];
  if (/glacier|mass balance|geodetic|cryosphere|himalaya/.test(text))
    return [
      { name: 'surface_elevation_change', units: 'm', longName: 'Surface elevation change since first survey', base: -0.6, amp: 0.3, noise: 0.05 },
      { name: 'ablation_rate', units: 'm w.e. d-1', longName: 'Daily ablation rate', base: 0.02, amp: 0.015, noise: 0.003 },
    ];
  if (/ocean|ctd|carbon|iron|transect|sea/.test(text))
    return [
      { name: 'sea_water_temperature', units: 'degC', longName: 'In-situ sea water temperature', base: 1.8, amp: 1.2, noise: 0.2 },
      { name: 'sea_water_salinity', units: 'PSU', longName: 'Practical salinity', base: 34, amp: 0.3, noise: 0.05 },
      { name: 'poc_flux', units: 'mg C m-2 d-1', longName: 'Particulate organic carbon flux', base: 45, amp: 15, noise: 5 },
    ];
  if (/power|fuel|chp|energy/.test(text))
    return [
      { name: 'electrical_output', units: 'kW', longName: 'Combined electrical output', base: 142, amp: 20, noise: 4 },
      { name: 'heat_recovered', units: 'kWth', longName: 'Recovered heat to hydronic loop', base: 92, amp: 10, noise: 3 },
    ];
  return [{ name: 'observation', units: '1', longName: 'Observed value', base: 10, amp: 3, noise: 1 }];
}

function series(item: ArchiveItem, hours: number) {
  const vars = variablesFor(item);
  const r = rng(item.id);
  const start = Date.UTC(item.year ?? 2024, 0, 1);
  const rows: { time: string; values: number[] }[] = [];
  for (let i = 0; i < hours; i++) {
    const phase = (2 * Math.PI * i) / 24;
    rows.push({
      time: new Date(start + i * 3600_000).toISOString().replace('.000', ''),
      values: vars.map((v) => round(v.base + v.amp * Math.sin(phase) + (r() - 0.5) * 2 * v.noise, 4)),
    });
  }
  return { vars, rows };
}

const SAMPLE_NOTE =
  'SYNTHETIC SAMPLE EXTRACT generated by POLARIS from archive metadata (synthetic values, 7 days hourly). Not an official NCPOR data product.';

export function datasetCdl(item: ArchiveItem): string {
  const { vars, rows } = series(item, 168);
  const name = (item.meta.fileName || item.id).replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9_]/g, '_');
  const lines = [
    `netcdf ${name} {`,
    'dimensions:',
    `\ttime = UNLIMITED ; // (${rows.length} currently)`,
    'variables:',
    '\tdouble time(time) ;',
    `\t\ttime:units = "hours since ${rows[0].time}" ;`,
    '\t\ttime:calendar = "standard" ;',
    ...vars.flatMap((v) => [
      `\tfloat ${v.name}(time) ;`,
      `\t\t${v.name}:units = "${v.units}" ;`,
      `\t\t${v.name}:long_name = "${v.longName}" ;`,
    ]),
    '',
    '// global attributes:',
    `\t\t:title = "${item.title.replace(/"/g, "'")}" ;`,
    '\t\t:institution = "POLARIS demo archive (synthetic sample extract; not an NCPOR data product)" ;',
    item.stationId ? `\t\t:station = "${item.stationId}" ;` : '',
    '\t\t:Conventions = "CF-1.8, ISO 19115" ;',
    `\t\t:license = "${item.meta.license || 'CC-BY 4.0'}" ;`,
    `\t\t:comment = "${SAMPLE_NOTE}" ;`,
    'data:',
    ` time = ${rows.map((_, i) => i).join(', ')} ;`,
    ...vars.map((v, vi) => ` ${v.name} = ${rows.map((row) => row.values[vi]).join(', ')} ;`),
    '}',
  ];
  return lines.filter((l) => l !== '').join('\n') + '\n';
}

export function datasetCsv(item: ArchiveItem): string {
  const { vars, rows } = series(item, 168);
  return [
    `# ${item.title}`,
    `# ${SAMPLE_NOTE}`,
    `# License: ${item.meta.license || 'CC-BY 4.0'}`,
    ['time_utc', ...vars.map((v) => `${v.name} (${v.units})`)].join(','),
    ...rows.map((r) => [r.time, ...r.values].join(',')),
  ].join('\n') + '\n';
}

/** Header shown in the dataset inspector (same structure as the download, without the data block). */
export function datasetHeader(item: ArchiveItem): string {
  const cdl = datasetCdl(item);
  return cdl.slice(0, cdl.indexOf('data:')).trimEnd() + '\n}';
}

export function datasetDownload(item: ArchiveItem): { filename: string; contentType: string; body: string } {
  const base = (item.meta.fileName || item.id).replace(/\.(nc|csv|gz|fastq|h5|hdf5)(\.gz)?$/i, '');
  if (String(item.meta.format).toUpperCase() === 'CSV') {
    return { filename: `${base}.sample.csv`, contentType: 'text/csv; charset=utf-8', body: datasetCsv(item) };
  }
  return { filename: `${base}.sample.cdl`, contentType: 'text/plain; charset=utf-8', body: datasetCdl(item) };
}

/** Hourly surface synoptic export for a station (last 72 h), centred on its baseline readings. */
export function synopticCsv(station: StationData, now = new Date()): string {
  const r = rng(station.id + now.toISOString().slice(0, 13));
  const base = {
    temp: num(station.temp),
    wind: num(station.windSpeed),
    pressure: num(station.pressure),
    solar: num(station.solarFlux),
  };
  const end = Math.floor(now.getTime() / 3600_000) * 3600_000;
  const rows = ['time_utc,air_temperature_degC,wind_speed_kt,pressure_hPa,solar_flux_Wm2'];
  for (let i = 71; i >= 0; i--) {
    const t = end - i * 3600_000;
    const phase = (2 * Math.PI * new Date(t).getUTCHours()) / 24;
    rows.push(
      [
        new Date(t).toISOString().replace('.000', ''),
        round(base.temp + 2.5 * Math.sin(phase) + (r() - 0.5) * 1.2, 1),
        round(Math.max(0, base.wind + 4 * Math.cos(phase) + (r() - 0.5) * 4), 1),
        round(base.pressure + (r() - 0.5) * 2.4, 1),
        round(Math.max(0, base.solar * (0.6 + 0.4 * Math.sin(phase)) + (r() - 0.5) * 30), 0),
      ].join(',')
    );
  }
  return [
    `# Surface synoptic export: ${station.name} (${station.code})`,
    `# ${station.coordinates} | ${station.elevation}`,
    '# SYNTHETIC SAMPLE EXTRACT: synthetic hourly values around the station baseline; not WMO-transmitted observations.',
    ...rows,
  ].join('\n') + '\n';
}

export function bibtex(item: ArchiveItem): string {
  const esc = (s: string) => String(s).replace(/[{}]/g, '');
  return [
    `@article{ncpor_${item.id.replace(/[^A-Za-z0-9]/g, '_')},`,
    `  title = {${esc(item.title)}},`,
    `  author = {${esc(item.meta.authors || 'NCPOR')}},`,
    `  journal = {${esc(item.meta.journal || 'NCPOR Polar Data Centre')}},`,
    `  year = {${item.year ?? new Date().getFullYear()}},`,
    item.doi ? `  doi = {${esc(item.doi)}},` : '',
    '  publisher = {National Centre for Polar and Ocean Research, Ministry of Earth Sciences, Govt of India}',
    '}',
  ]
    .filter(Boolean)
    .join('\n') + '\n';
}

/** ISO 19115-flavoured metadata record for any archive item. */
export function metadataRecord(item: ArchiveItem, links: { id: string; title: string; type: string; relation: string }[]) {
  return {
    fileIdentifier: item.id,
    hierarchyLevel: item.type,
    title: item.title,
    abstract: item.summary,
    description: item.body || undefined,
    keywords: item.tags,
    topicCategory: item.domain,
    temporalExtent: item.year ? { year: item.year, date: item.date } : undefined,
    station: item.stationId,
    identifier: item.doi ? { doi: item.doi, url: `https://doi.org/${item.doi}` } : undefined,
    distribution: item.url ? { url: item.url } : undefined,
    pointOfContact: 'NCPOR Polar Data Centre, Vasco da Gama, Goa',
    license: item.meta.license || 'CC-BY 4.0',
    sampleRecord: Boolean(item.meta.sample),
    additionalInfo: item.meta,
    relatedRecords: links,
    metadataStandard: 'ISO 19115 (simplified JSON)',
    generatedAt: new Date().toISOString(),
  };
}

export function proposalTemplate(): string {
  return `================================================================================
MINISTRY OF EARTH SCIENCES (MoES) - GOVERNMENT OF INDIA
NATIONAL CENTRE FOR POLAR AND OCEAN RESEARCH (NCPOR), GOA
RESEARCH PROPOSAL TEMPLATE - 46TH ISEA & UPCOMING ARCTIC SEASON
================================================================================

1. PROJECT TITLE:
2. PRINCIPAL INVESTIGATOR (PI) DETAILS:
   - Full Name:
   - Designation & Affiliation:
   - Email & Mobile:
   - Institutional Endorsement Certificate Ref:

3. TARGET OBSERVATIONAL PLATFORM:
   [ ] Bharati Research Station (Larsemann Hills)
   [ ] Maitri Station (Schirmacher Oasis)
   [ ] Himadri Station (Ny-Alesund, Svalbard)
   [ ] Himansh Observatory (Spiti Valley, Himalayas)
   [ ] ORV Sagar Nidhi / Sagar Kanya Oceanic Cruise

4. SCIENTIFIC OBJECTIVES & RELEVANCE TO NATIONAL POLAR PRIORITIES:
   - Executive Summary (max 300 words):
   - Teleconnections to Indian Monsoon / Climate Change:
   - Madrid Protocol Environmental Impact Assessment:

5. LOGISTICAL REQUIREMENTS:
   - Number of berths requested:
   - Hazardous chemicals or radio-isotopes (if any):
   - Power & cargo weight allocation (kg):

6. DATA SHARING DECLARATION:
   Under MoES Open Data Policy, all curated datasets will be archived in the
   NCPOR Polar Data Centre within 12 months of voyage completion.

Submit online through the POLARIS portal (Call for Proposals > Submit).
================================================================================
`;
}
