import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { adminToken } from '../lib/api';
import { isReviewerRole, useAuth } from '../lib/auth';

const STATUS_STYLE: Record<string, { label: string; cls: string; title: string }> = {
  OFFICIAL: { label: 'Official', cls: 'bg-emerald-100 text-emerald-800', title: 'Published by NCPOR / MoES' },
  VERIFIED: { label: 'Verified', cls: 'bg-teal-100 text-teal-800', title: 'Checked against an authoritative source by a reviewer' },
  EXTERNAL: { label: 'Open registry', cls: 'bg-indigo-100 text-indigo-800', title: 'Metadata imported from Crossref or PANGAEA (with DOI); POLARIS did not produce the underlying work' },
  UNVERIFIED: { label: 'Unverified', cls: 'bg-slate-200 text-slate-700', title: 'Compiled from public descriptions; not yet verified' },
  SAMPLE: { label: 'Sample', cls: 'bg-amber-100 text-amber-800', title: 'Illustrative demo record, not real data' },
  SYNTHETIC: { label: 'Synthetic sample extract', cls: 'bg-orange-100 text-orange-800', title: 'Values generated by POLARIS for demonstration' },
  AI_GENERATED: { label: 'AI generated', cls: 'bg-violet-100 text-violet-800', title: 'Drafted by a language model; needs human review' },
  TEMPLATE: { label: 'Template', cls: 'bg-sky-100 text-sky-800', title: 'Assembled by a deterministic template from the record' },
};

export function DataStatusBadge({ status, className = '' }: { status?: string | null; className?: string }) {
  const s = STATUS_STYLE[status ?? ''] ?? STATUS_STYLE.UNVERIFIED;
  return (
    <span title={s.title} className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold whitespace-nowrap ${s.cls} ${className}`}>
      {s.label}
    </span>
  );
}

export function PageHeader({ title, text, children }: { title: string; text?: string; children?: React.ReactNode }) {
  return (
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-3 mb-6">
      <div className="max-w-3xl">
        <h1 className="font-['Space_Grotesk'] text-2xl md:text-3xl font-bold tracking-tight">{title}</h1>
        {text && <p className="sci-muted text-sm mt-1">{text}</p>}
      </div>
      {children}
    </div>
  );
}

export function Page({ children }: { children: React.ReactNode }) {
  return (
    <div className="sci-page min-h-[70vh]">
      <div className="w-full max-w-[1440px] mx-auto px-4 md:px-8 py-6 md:py-10">{children}</div>
    </div>
  );
}

/** Asks for the admin token once per browser session (sessionStorage), then renders children. */
export function AdminGate({ children }: { children: (logout: () => void) => React.ReactNode }) {
  const { user, loading } = useAuth();
  const [token, setToken] = useState(adminToken.get());
  const [draft, setDraft] = useState('');
  if (loading) return <p className="text-sm sci-muted">Loading…</p>;
  if (isReviewerRole(user)) return <>{children(() => undefined)}</>;
  if (token) {
    return (
      <>
        {children(() => {
          adminToken.set('');
          setToken('');
        })}
      </>
    );
  }
  return (
    <div className="sci-card p-6 max-w-md">
      <h2 className="font-semibold mb-1">Reviewer sign-in</h2>
      <p className="sci-muted text-sm mb-3">
        {user ? `You are signed in as a ${user.role}. Reviewing needs the reviewer role; ask an admin, or use the admin token.` : (
          <>
            <Link to="/login" className="underline">Sign in</Link> with a reviewer account, or use the admin token.
          </>
        )}
      </p>
      <p className="sci-muted text-sm mb-4">
        Enter the admin token. It is printed in the server log at start-up, or set with <span className="sci-mono">ADMIN_TOKEN</span> in <span className="sci-mono">.env</span>.
      </p>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          adminToken.set(draft.trim());
          setToken(draft.trim());
        }}
        className="flex gap-2"
      >
        <input type="password" value={draft} onChange={(e) => setDraft(e.target.value)} className="sci-input flex-1" placeholder="Admin token" aria-label="Admin token" />
        <button className="sci-btn" disabled={!draft.trim()}>
          Continue
        </button>
      </form>
    </div>
  );
}

export function ErrorNote({ error }: { error: string | null }) {
  if (!error) return null;
  return <p className="text-sm mt-2" style={{ color: 'var(--pol-bad)' }}>{error}</p>;
}
